---
title       : Welcome to selfman's World! 
subtitle    : ... a new approach to ....
author      : Bernhard Thoni the Great
job         : ICT manager
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Read and Delete


--- .class2 #slide2 bg:url(http://www.dream-wallpaper.com/free-wallpaper/art-wallpaper/background-color-1-wallpaper/1920x1200/free-wallpaper-15.jpg) 

## Slide 2

*Here* _comes_ my first code chunk  

[Come-and-enter-here!](http://www.kanubau.de)

here some latex-type $x^2$ formatting.

```{r chunk_computation}
a<-5
b<-6
c<-a+b
``` 

The result of this computation is `r c`.  

--- .class #slide3 .class3 bg:green

## Slide 3

```{r chunk_plotting, echo=T, message=FALSE}
#library('mtcars')
plot(mtcars$mpg, mtcars$cyl)

```

--- .class4 #slide4 &radio 

## Slide 4

<center>Quiz me up!</center>  
  
What is 5 + 6???

1. It gives 7
2. _It gives 11_
3. It gives 8
4. Dunno!  

*** .hint   
What about keying it in your calculator?
*** .explanation   
life could be that simple, if.....
  






